name: Build and Release

on:
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install PHP Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install Node Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Checkout Set Git Action User
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check if builds branch exists
        run: |
          git ls-remote --exit-code --heads origin builds
          if [ $? -eq 0 ]; then
            echo "Builds branch exists"
            git checkout -b builds origin/builds
            git pull origin builds
          else
            echo "Builds branch does not exist"
            git checkout -b builds
          fi
      
      - name: Commit changes
        run: |
          git add --force . 
          git commit -m "Built plugin version"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: builds

      - name: Bump version and Create a Git Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
