name: Build and Release

on:
  workflow_dispatch:
    inputs:
      bumpLevel:
        required: true
        default: patch
        description: 'The level of bump to apply to the version number'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  build:
    uses: johnkraczek/BuildAndTagWordpressPlugin/.github/workflows/build_and_tag.yml@main
    with:
      bumpLevel: ${{ github.event.inputs.bumpLevel }}
      root_php_file: 'PluginToolsServer.php'
